//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gfe {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gfe.Texte", typeof(Texte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /H or /?       : Display this help.
        ////S                  : Extract source files in the current directory.
        ////U [&lt;path&gt;] : Download the lastest version of the software
        ////O &lt;path&gt;   : Open the path without asking to the user.
        ////R                  : Delete every file of the software on the computer.
        ///
        ///To get more help, go to : http://github.com/Penta/GFE/wiki.
        /// </summary>
        public static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de votre ancien fond d&apos;écran n&apos;existe plus, il n&apos;a donc pas été remit en place..
        /// </summary>
        public static string AncienFondSupprimé {
            get {
                return ResourceManager.GetString("AncienFondSupprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Argument..
        /// </summary>
        public static string ArgumentInvalide {
            get {
                return ResourceManager.GetString("ArgumentInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to specify a path !.
        /// </summary>
        public static string AucunCheminParamètre {
            get {
                return ResourceManager.GetString("AucunCheminParamètre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a directory!.
        /// </summary>
        public static string AucunDossier {
            get {
                return ResourceManager.GetString("AucunDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun fichier n&apos;est selectionné..
        /// </summary>
        public static string AucunFichierAffiché {
            get {
                return ResourceManager.GetString("AucunFichierAffiché", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun fichier d&apos;image dans ce dossier !.
        /// </summary>
        public static string AucunFichierDossier {
            get {
                return ResourceManager.GetString("AucunFichierDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement....
        /// </summary>
        public static string Chargement {
            get {
                return ResourceManager.GetString("Chargement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande executée :.
        /// </summary>
        public static string CommandeExecutée {
            get {
                return ResourceManager.GetString("CommandeExecutée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer.
        /// </summary>
        public static string Commencer {
            get {
                return ResourceManager.GetString("Commencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment appliquer cette image en tant que fond d&apos;écran de votre bureau ?.
        /// </summary>
        public static string ConfirmationAppliquerTitre {
            get {
                return ResourceManager.GetString("ConfirmationAppliquerTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string ConfirmationTitre {
            get {
                return ResourceManager.GetString("ConfirmationTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose your wallpaper&apos;s directory..
        /// </summary>
        public static string DescriptionSelectionDossier {
            get {
                return ResourceManager.GetString("DescriptionSelectionDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one of the directories is invalid!.
        /// </summary>
        public static string DossierInvalide {
            get {
                return ResourceManager.GetString("DossierInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue durant la remise de votre ancien fond d&apos;écran !.
        /// </summary>
        public static string ErreurAncienFond {
            get {
                return ResourceManager.GetString("ErreurAncienFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when the software was updating!
        ///
        ///Error: .
        /// </summary>
        public static string ErreurInstMaj {
            get {
                return ResourceManager.GetString("ErreurInstMaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de le lire ce dossier !.
        /// </summary>
        public static string ErreurLectureDossier {
            get {
                return ResourceManager.GetString("ErreurLectureDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue à la récupération de la liste des fichiers du dossier .
        /// </summary>
        public static string ErreurLectureListe {
            get {
                return ResourceManager.GetString("ErreurLectureListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue durant le lancement du logiciel externe !.
        /// </summary>
        public static string ErreurLogicielExterne {
            get {
                return ResourceManager.GetString("ErreurLogicielExterne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The software is unable to check for updates! Do you still have internet? The update server is still online?.
        /// </summary>
        public static string ErreurMaj {
            get {
                return ResourceManager.GetString("ErreurMaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est surevenue durant la modification du registre !\n\nErreur :\n.
        /// </summary>
        public static string ErreurMenuContextuel {
            get {
                return ResourceManager.GetString("ErreurMenuContextuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue durant la modification du nom !.
        /// </summary>
        public static string ErreurModificationNom {
            get {
                return ResourceManager.GetString("ErreurModificationNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when the software was reading the registry!
        ///
        ///Your configuration has been reset..
        /// </summary>
        public static string ErreurRegistre {
            get {
                return ResourceManager.GetString("ErreurRegistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  sous-dossier(s) n&apos;a ou n&apos;ont pas été lu(s) !\n\nCette erreur est non fatale..
        /// </summary>
        public static string ErreurSousDossier {
            get {
                return ResourceManager.GetString("ErreurSousDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred during the download of the source files..
        /// </summary>
        public static string ErreurTéléchargementSources {
            get {
                return ResourceManager.GetString("ErreurTéléchargementSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string ErreurTitre {
            get {
                return ResourceManager.GetString("ErreurTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier a bien été renommé !.
        /// </summary>
        public static string FichierRenommé {
            get {
                return ResourceManager.GetString("FichierRenommé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fond d&apos;écran sera actif une fois le logiciel fermé !.
        /// </summary>
        public static string FondAppliqué {
            get {
                return ResourceManager.GetString("FondAppliqué", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  sur .
        /// </summary>
        public static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez sur commencer pour selectionner un fichier..
        /// </summary>
        public static string InfobulleNomStart {
            get {
                return ResourceManager.GetString("InfobulleNomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string InfoTitre {
            get {
                return ResourceManager.GetString("InfoTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You software is up to date!.
        /// </summary>
        public static string LogicielAJour {
            get {
                return ResourceManager.GetString("LogicielAJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An update is available!
        ///
        ///The software needs to restart to download the update..
        /// </summary>
        public static string MajDispo {
            get {
                return ResourceManager.GetString("MajDispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your software has been updated to the version .
        /// </summary>
        public static string MajInstallée {
            get {
                return ResourceManager.GetString("MajInstallée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update done!.
        /// </summary>
        public static string MajInstalléeTitre {
            get {
                return ResourceManager.GetString("MajInstalléeTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your specified path is not valid !.
        /// </summary>
        public static string MauvaisCheminParamètre {
            get {
                return ResourceManager.GetString("MauvaisCheminParamètre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez maintenant lancer le Gestionnaire de Fond d&apos;Écran dans le menu contextuel d&apos;un dossier ! (clic droit)\n\nVeuillez désactiver cette option avant de supprimer ou déplacer cet exécutable..
        /// </summary>
        public static string MenuContextuelAppliqué {
            get {
                return ResourceManager.GetString("MenuContextuelAppliqué", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;entrée dans le menu contextuel a bien été supprimée..
        /// </summary>
        public static string MenuContextuelSupprimé {
            get {
                return ResourceManager.GetString("MenuContextuelSupprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display wallpapers in this directory.
        /// </summary>
        public static string MenuContextuelTexte {
            get {
                return ResourceManager.GetString("MenuContextuelTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to add this path to the existing one(s)?
        ///
        ///Press No will replace all the current values !.
        /// </summary>
        public static string QuestionSelection {
            get {
                return ResourceManager.GetString("QuestionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recharger.
        /// </summary>
        public static string Recharger {
            get {
                return ResourceManager.GetString("Recharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The filename cannot be empty!.
        /// </summary>
        public static string RenommerFichierVide {
            get {
                return ResourceManager.GetString("RenommerFichierVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The number is too high!.
        /// </summary>
        public static string SautTropGrand {
            get {
                return ResourceManager.GetString("SautTropGrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type a positive number!.
        /// </summary>
        public static string SautTropPetit {
            get {
                return ResourceManager.GetString("SautTropPetit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type a number!.
        /// </summary>
        public static string SautVide {
            get {
                return ResourceManager.GetString("SautVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seulement une seule instance du logiciel peut être lancée à la fois !.
        /// </summary>
        public static string SeulementUneInstance {
            get {
                return ResourceManager.GetString("SeulementUneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success!.
        /// </summary>
        public static string SuccèsTitre {
            get {
                return ResourceManager.GetString("SuccèsTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string Suivant {
            get {
                return ResourceManager.GetString("Suivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source files has been downloaded from GitHub!.
        /// </summary>
        public static string TéléchargementSources {
            get {
                return ResourceManager.GetString("TéléchargementSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer.
        /// </summary>
        public static string Terminer {
            get {
                return ResourceManager.GetString("Terminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wallpaper Manager.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every single file created by the Wallpaper Manager has been deleted, you can now delete this executable to totally remove the Wallpaper Manager from your computer!.
        /// </summary>
        public static string ToutSupprimé {
            get {
                return ResourceManager.GetString("ToutSupprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue..
        /// </summary>
        public static string UneErreurSurvenue {
            get {
                return ResourceManager.GetString("UneErreurSurvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 sur .
        /// </summary>
        public static string ZeroFraction {
            get {
                return ResourceManager.GetString("ZeroFraction", resourceCulture);
            }
        }
    }
}
