//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gfe.Langues {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gfe.Langues.Texte", typeof(Texte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /H or /?       : Display this help.
        ////S                  : Extract source files in the current directory.
        ////U [&lt;path&gt;] : Download the lastest version of the software
        ////O &lt;path&gt;   : Open the path without asking to the user.
        ////R                  : Delete every file of the software on the computer.
        ///
        ///To get more help, go to : http://github.com/Penta/GFE/wiki.
        /// </summary>
        public static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file of your original wallpaper doesn&apos;t exist anymore, it can&apos;t be reapplied..
        /// </summary>
        public static string AncienFondSupprimé {
            get {
                return ResourceManager.GetString("AncienFondSupprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Argument..
        /// </summary>
        public static string ArgumentInvalide {
            get {
                return ResourceManager.GetString("ArgumentInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to specify a path !.
        /// </summary>
        public static string AucunCheminParamètre {
            get {
                return ResourceManager.GetString("AucunCheminParamètre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a directory!.
        /// </summary>
        public static string AucunDossier {
            get {
                return ResourceManager.GetString("AucunDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file at the moment..
        /// </summary>
        public static string AucunFichierAffiché {
            get {
                return ResourceManager.GetString("AucunFichierAffiché", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no image file in this directory!.
        /// </summary>
        public static string AucunFichierDossier {
            get {
                return ResourceManager.GetString("AucunFichierDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string Chargement {
            get {
                return ResourceManager.GetString("Chargement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose the external software for the file edition....
        /// </summary>
        public static string ChoixExterneTitre {
            get {
                return ResourceManager.GetString("ChoixExterneTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command:.
        /// </summary>
        public static string CommandeExecutée {
            get {
                return ResourceManager.GetString("CommandeExecutée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string Commencer {
            get {
                return ResourceManager.GetString("Commencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to apply this picture as your new desktop wallpaper?.
        /// </summary>
        public static string ConfirmationAppliquerTitre {
            get {
                return ResourceManager.GetString("ConfirmationAppliquerTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string ConfirmationTitre {
            get {
                return ResourceManager.GetString("ConfirmationTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose your wallpaper&apos;s directory..
        /// </summary>
        public static string DescriptionSelectionDossier {
            get {
                return ResourceManager.GetString("DescriptionSelectionDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one of the directories is invalid!.
        /// </summary>
        public static string DossierInvalide {
            get {
                return ResourceManager.GetString("DossierInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This directory is done!
        ///
        ///Do you want to close this software?.
        /// </summary>
        public static string DossierTerminé {
            get {
                return ResourceManager.GetString("DossierTerminé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when the Wallpaper Manager tried to reapply your original wallpaper!.
        /// </summary>
        public static string ErreurAncienFond {
            get {
                return ResourceManager.GetString("ErreurAncienFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à : this file cannot be read, do you want to delete it?.
        /// </summary>
        public static string ErreurChargementFichier {
            get {
                return ResourceManager.GetString("ErreurChargementFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file in this directory selection..
        /// </summary>
        public static string ErreurDossierVide {
            get {
                return ResourceManager.GetString("ErreurDossierVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when the software was updating!
        ///
        ///Error: .
        /// </summary>
        public static string ErreurInstMaj {
            get {
                return ResourceManager.GetString("ErreurInstMaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to read this directory!.
        /// </summary>
        public static string ErreurLectureDossier {
            get {
                return ResourceManager.GetString("ErreurLectureDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when the software tried to create the file list of the directory .
        /// </summary>
        public static string ErreurLectureListe {
            get {
                return ResourceManager.GetString("ErreurLectureListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to choose a valid file!.
        /// </summary>
        public static string ErreurListeFichier {
            get {
                return ResourceManager.GetString("ErreurListeFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred during the execution of the external software!.
        /// </summary>
        public static string ErreurLogicielExterne {
            get {
                return ResourceManager.GetString("ErreurLogicielExterne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The software is unable to check for updates! Do you still have internet? The update server is still online?.
        /// </summary>
        public static string ErreurMaj {
            get {
                return ResourceManager.GetString("ErreurMaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred during the modification of the registry!
        ///
        ///Error: .
        /// </summary>
        public static string ErreurMenuContextuel {
            get {
                return ResourceManager.GetString("ErreurMenuContextuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred during the modification of the name !.
        /// </summary>
        public static string ErreurModificationNom {
            get {
                return ResourceManager.GetString("ErreurModificationNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when the software was reading the registry!
        ///
        ///Your configuration has been reset..
        /// </summary>
        public static string ErreurRegistre {
            get {
                return ResourceManager.GetString("ErreurRegistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  sub-directory(ies) cannot be read!
        /// 
        ///This error is not fatal..
        /// </summary>
        public static string ErreurSousDossier {
            get {
                return ResourceManager.GetString("ErreurSousDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred during the download of the source files..
        /// </summary>
        public static string ErreurTéléchargementSources {
            get {
                return ResourceManager.GetString("ErreurTéléchargementSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string ErreurTitre {
            get {
                return ResourceManager.GetString("ErreurTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executables (*.exe)|*.exe|All files (*.*)|*.*.
        /// </summary>
        public static string ExtensionsExterne {
            get {
                return ResourceManager.GetString("ExtensionsExterne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file has been renamed!.
        /// </summary>
        public static string FichierRenommé {
            get {
                return ResourceManager.GetString("FichierRenommé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This wallpaper will be displayed as your main wallpaper when you will close the Wallpaper Manager..
        /// </summary>
        public static string FondAppliqué {
            get {
                return ResourceManager.GetString("FondAppliqué", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  on .
        /// </summary>
        public static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on Start to display the first file..
        /// </summary>
        public static string InfobulleNomStart {
            get {
                return ResourceManager.GetString("InfobulleNomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string InfoTitre {
            get {
                return ResourceManager.GetString("InfoTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your software is up to date!.
        /// </summary>
        public static string LogicielAJour {
            get {
                return ResourceManager.GetString("LogicielAJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An update is available!
        ///
        ///The software needs to restart to download the update..
        /// </summary>
        public static string MajDispo {
            get {
                return ResourceManager.GetString("MajDispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your software has been updated to the version .
        /// </summary>
        public static string MajInstallée {
            get {
                return ResourceManager.GetString("MajInstallée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update done!.
        /// </summary>
        public static string MajInstalléeTitre {
            get {
                return ResourceManager.GetString("MajInstalléeTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your specified path is not valid !.
        /// </summary>
        public static string MauvaisCheminParamètre {
            get {
                return ResourceManager.GetString("MauvaisCheminParamètre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can now start the Wallpaper Manager with the context menu of a directory! (right click)
        ///
        ///Please desactivate this option if you move or delete this executable file..
        /// </summary>
        public static string MenuContextuelAppliqué {
            get {
                return ResourceManager.GetString("MenuContextuelAppliqué", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The entry in your context menu has been deleted..
        /// </summary>
        public static string MenuContextuelSupprimé {
            get {
                return ResourceManager.GetString("MenuContextuelSupprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Try all the wallpapers in this directory.
        /// </summary>
        public static string MenuContextuelTexte {
            get {
                return ResourceManager.GetString("MenuContextuelTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to reset your configuration?.
        /// </summary>
        public static string MessageReinitialisation {
            get {
                return ResourceManager.GetString("MessageReinitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File number:.
        /// </summary>
        public static string NombreFichierListe {
            get {
                return ResourceManager.GetString("NombreFichierListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to add this path to the existing one(s)?
        ///
        ///Press No will replace all the current values !.
        /// </summary>
        public static string QuestionSelection {
            get {
                return ResourceManager.GetString("QuestionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload.
        /// </summary>
        public static string Recharger {
            get {
                return ResourceManager.GetString("Recharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to restart the application to change the language!.
        /// </summary>
        public static string RedémarrageLangue {
            get {
                return ResourceManager.GetString("RedémarrageLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your configuration has been reset!.
        /// </summary>
        public static string ReinitialisationFaite {
            get {
                return ResourceManager.GetString("ReinitialisationFaite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The filename cannot be empty!.
        /// </summary>
        public static string RenommerFichierVide {
            get {
                return ResourceManager.GetString("RenommerFichierVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The number is too high!.
        /// </summary>
        public static string SautTropGrand {
            get {
                return ResourceManager.GetString("SautTropGrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type a positive number!.
        /// </summary>
        public static string SautTropPetit {
            get {
                return ResourceManager.GetString("SautTropPetit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type a number!.
        /// </summary>
        public static string SautVide {
            get {
                return ResourceManager.GetString("SautVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only one instance of the software is allowed at the same time!.
        /// </summary>
        public static string SeulementUneInstance {
            get {
                return ResourceManager.GetString("SeulementUneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success!.
        /// </summary>
        public static string SuccèsTitre {
            get {
                return ResourceManager.GetString("SuccèsTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        public static string Suivant {
            get {
                return ResourceManager.GetString("Suivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to delete this wallpaper?.
        /// </summary>
        public static string Suppression {
            get {
                return ResourceManager.GetString("Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source files has been downloaded from GitHub!.
        /// </summary>
        public static string TéléchargementSources {
            get {
                return ResourceManager.GetString("TéléchargementSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string Terminer {
            get {
                return ResourceManager.GetString("Terminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wallpaper Manager.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every single file created by the Wallpaper Manager has been deleted, you can now delete this executable to totally remove the Wallpaper Manager from your computer!.
        /// </summary>
        public static string ToutSupprimé {
            get {
                return ResourceManager.GetString("ToutSupprimé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred..
        /// </summary>
        public static string UneErreurSurvenue {
            get {
                return ResourceManager.GetString("UneErreurSurvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajust.
        /// </summary>
        public static string ValeurAjuster {
            get {
                return ResourceManager.GetString("ValeurAjuster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à White.
        /// </summary>
        public static string ValeurBlanc {
            get {
                return ResourceManager.GetString("ValeurBlanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue.
        /// </summary>
        public static string ValeurBleu {
            get {
                return ResourceManager.GetString("ValeurBleu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light blue.
        /// </summary>
        public static string ValeurBleuClair {
            get {
                return ResourceManager.GetString("ValeurBleuClair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center.
        /// </summary>
        public static string ValeurCentrer {
            get {
                return ResourceManager.GetString("ValeurCentrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extend.
        /// </summary>
        public static string ValeurEtendre {
            get {
                return ResourceManager.GetString("ValeurEtendre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stretch.
        /// </summary>
        public static string ValeurEtirer {
            get {
                return ResourceManager.GetString("ValeurEtirer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grey.
        /// </summary>
        public static string ValeurGris {
            get {
                return ResourceManager.GetString("ValeurGris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark grey.
        /// </summary>
        public static string ValeurGrisFoncé {
            get {
                return ResourceManager.GetString("ValeurGrisFoncé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yellow.
        /// </summary>
        public static string ValeurJaune {
            get {
                return ResourceManager.GetString("ValeurJaune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marron.
        /// </summary>
        public static string ValeurMarron {
            get {
                return ResourceManager.GetString("ValeurMarron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mosaique.
        /// </summary>
        public static string ValeurMosaique {
            get {
                return ResourceManager.GetString("ValeurMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Black.
        /// </summary>
        public static string ValeurNoir {
            get {
                return ResourceManager.GetString("ValeurNoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Orange.
        /// </summary>
        public static string ValeurOrange {
            get {
                return ResourceManager.GetString("ValeurOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill.
        /// </summary>
        public static string ValeurRemplir {
            get {
                return ResourceManager.GetString("ValeurRemplir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pink.
        /// </summary>
        public static string ValeurRose {
            get {
                return ResourceManager.GetString("ValeurRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red.
        /// </summary>
        public static string ValeurRouge {
            get {
                return ResourceManager.GetString("ValeurRouge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Green.
        /// </summary>
        public static string ValeurVert {
            get {
                return ResourceManager.GetString("ValeurVert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purple.
        /// </summary>
        public static string ValeurViolet {
            get {
                return ResourceManager.GetString("ValeurViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 on .
        /// </summary>
        public static string ZeroFraction {
            get {
                return ResourceManager.GetString("ZeroFraction", resourceCulture);
            }
        }
    }
}
